In [16]:
import shutil
import pandas as pd

shutil.copyfile('./all/all1.txt', './all/all1.csv')
data = pd.read_csv('./all/all1.csv')
data.head()

,control_number,student1,student2,student3,university,prize,Unnamed: 6
0,2200002,Jiaying Yin,Yingxin Liu,Zhehan Qi,BNU-HKBU United International College,Successful Participant,NaN
1,2200003,Ding Xueqi,Wang Yian,Liu Yuxuan,BNU-HKBU United International College,Successful Participant,NaN
2,2200004,Li Sirui,Peng Bo,Xiao Dingwen,BNU-HKBU United International College,Honorable Mention,NaN
3,2200005,He Yandi,Fu Weichen,Sun Qihao,BNU-HKBU United International College,Successful Participant,NaN
4,2200006,Hansheng Li,Hongx1 Zhang,Haoxuan Feng,BNU-HKBU United International College,Successful Participant,NaN

In [17]:
data['university'].value_counts()

BNU-HKBU United International College            30
Honorable Mention                                 3
Wuhan University                                  2
Jiamusi University                                2
Successful Participant                            2
Tianjin University                                2
Shenzhen University                               2
China Jiliang University                          1
Hainan university                                 1
Maynooth Engineering                              1
Shanghai University                               1
Disqualified - P                                  1
Guizhou University                                1
University of Science and Technology of China     1
Lanzhou University                                1
ChongQing University of arts and sciences         1
China University of Geosciences (wu han)          1
NortheastAgricultural University                  1
China University of Petroleum (EastChina)         1
Name: university, dtype: int64

In [18]:
data['prize'].value_counts()

Successful Participant    31
Honorable Mention         11
Disqualified - P           3
Meritorious Winner         3
Unsuccessful - I           1
Name: prize, dtype: int64

In [20]:
your_univ_result=data.loc[data['university']=='BNU-HKBU United International College']
your_univ_result

,control_number,student1,student2,student3,university,prize,Unnamed: 6
0,2200002,Jiaying Yin,Yingxin Liu,Zhehan Qi,BNU-HKBU United International College,Successful Participant,NaN
1,2200003,Ding Xueqi,Wang Yian,Liu Yuxuan,BNU-HKBU United International College,Successful Participant,NaN
2,2200004,Li Sirui,Peng Bo,Xiao Dingwen,BNU-HKBU United International College,Honorable Mention,NaN
3,2200005,He Yandi,Fu Weichen,Sun Qihao,BNU-HKBU United International College,Successful Participant,NaN
4,2200006,Hansheng Li,Hongx1 Zhang,Haoxuan Feng,BNU-HKBU United International College,Successful Participant,NaN
9,2200011,Xu Jiayun,Hou Huantong,Chen Bingshen,BNU-HKBU United International College,Successful Participant,NaN
10,2200012,Liu Yiy1,Wu Ruibing,Yu Xiaotong,BNU-HKBU United International College,Honorable Mention,NaN
11,2200013,Zian Wang,Yuanx1 Peng,Teng Fei,BNU-HKBU United International College,Honorable Mention,NaN
12,2200014,Fan Yuchen,Zhang Yihan,Guo Wenhao,BNU-HKBU United International College,Successful Participant,NaN
13,2200015,Qian Yaqi,Huang Huiran,Wu Zhuogen,BNU-HKBU United International College,Meritorious Winner,NaN
14,2200016,Zhao Zian,Zhang Yan,Yu Haoming,BNU-HKBU United International College,Honorable Mention,NaN
15,2200017,Li Yifan,Fei Yue,Tang Linchuan,BNU-HKBU United International College,Successful Participant,NaN
16,2200018,Zhang Le,Deng X1aoqi,Xie Suiwel,BNU-HKBU United International College,Successful Participant,NaN
17,2200019,LI Xuran,SUN Xiaoxuan,LU Qianqian,BNU-HKBU United International College,Successful Participant,NaN
18,2200020,Chen Yangyang,Liu Lefei,He Zhiying,BNU-HKBU United International College,Successful Participant,NaN
19,2200021,Huang Chujun,Liu Anyan,Wu You,BNU-HKBU United International College,Honorable Mention,NaN
20,2200023,Chen Xinming,Li Qiuxian,Ma Tiancheng,BNU-HKBU United International College,Successful Participant,NaN
21,2200024,ZHENG YUHAN,XUE SHAOJIE,LIN XIAOTAO,BNU-HKBU United International College,Meritorious Winner,NaN
22,2200025,ZHANG Xiaopeli,ZHANG Xueying,BI X1,BNU-HKBU United International College,Honorable Mention,NaN
23,2200026,Zhang Jinwei,Xiao Lefu,Liu Xinhui,BNU-HKBU United International College,Honorable Mention,NaN
27,2200030,Wu Wei,Chen Zhenzhen,Gao Junxiu,BNU-HKBU United International College,Successful Participant,NaN
28,2200031,Jiang Liyao,Jiang Guilin,Zuo Shuaitao,BNU-HKBU United International College,Successful Participant,NaN
29,2200032,LIU Minghao,HUANG Zhaojia,SA Xingyun,BNU-HKBU United International College,Successful Participant,NaN
30,2200033,Xiao Zhengtao,Feng Yaopeng,Chen Zhengyu,BNU-HKBU United International College,Successful Participant,NaN
31,2200034,Xia Linhan,Huang Yuhao,Hou Yishi,BNU-HKBU United International College,Successful Participant,NaN
32,2200035,Li Zuka1,Lin Runsheng,Xing Zehan,BNU-HKBU United International College,Meritorious Winner,NaN
33,2200036,CHEN HONGXI,CHEN MEITONG,HU XINYUE,BNU-HKBU United International College,Successful Participant,NaN
34,2200037,Li Mohan,Luo Meimei,Lu Chengjie,BNU-HKBU United International College,Successful Participant,NaN
35,2200038,Zhang Lingshuo,Lu Hongy1,Pang Haohua,BNU-HKBU United International College,Successful Participant,NaN
36,2200039,Tian Yuxin,Wang Ziyu,Yang Yu,BNU-HKBU United International College,Successful Participant,NaN

In [21]:
your_univ_result['prize'].value_counts()

Successful Participant    20
Honorable Mention          7
Meritorious Winner         3
Name: prize, dtype: int64